### ISSUE TITLE
Additional Actions Support, Custom URL Path

### ISSUE THREAD

**Issue by ooglek** [CLSystems/sas-api-client#4]
Hey -- I'm a fan of improving existing code rather than forking and duplicating work.

### Pull Request Offer

I can probably knock out most of these and submit a Pull Request. I'll do so if I hear back from you in a day or so and you want me to do it, and you'll merge it quickly. If not, I'll likely fork this code and create my own version.

### Custom Service Path
Your code seems to be calling `/x.cfm` and my URL is a different path (dunno why). Need a `SetServicePath` method and private class variable for that.

### Missing Actions
There are a bunch of actions that don't seem to be implemented:

https://account.shareasale.com/m-apiips.cfm

Action List:

1. void -- Void a Transaction
2. edit -- Edit Transaction
3. ??? - Locate a Transaction (action name TBD)
4. ??? - New Transaction (action name TBD)
5. reference -- New Transaction Crediting the same Affiliate as a Previous (reference) transaction
6. transactiondetail -- Transaction Detail Report
7. weeklyprogress -- Weekly Progress Report
8. affiliatetimestamp -- Timespan Affiliate Summary
9. datafeeddownloads -- Datafeed and FTP Downloads
10. todayataglance -- Today at a Glance
11. staterevenue -- US State Revenue
12. report-affiliate -- Your Affiliate List
13. transactioneditreport -- Previously Edited Transactions Report
14. transactionvoidreport -- Previously Voided Transactions Report
15. bannerreport -- Banner Report
16. affiliateTags -- Affiliate Tags
17. bannerList -- Banner/Text Link List
18. bannerUpload -- Banner/Text Link Upload
19. bannerEdit -- Banner/Text Link Edit
20. dealList
21. dealUpload
22. dealEdit
23. approveAffiliate
24. declineAffiliate
25. MassTagAffiliates

**Comment by orbex** [comment]
Please feel free to add what you need/want and submit a PR.
It will be reviewed and merged asap.

**Comment by ooglek** [comment]
After digging into this, your code is specifically for Affiliates, while what I want to do is specifically for Merchants.

I'm gonna fork your code and rebuild for Merchants. If you wanna grab it after I'm done and make your code work for both Affiliates and Merchants, sweet! They are pretty similar, here are the differences:

1. Query must contain `merchantID` rather than `affiliateId`
2. Some Actions do not return XML, mostly Transaction Requests (this is pretty annoying because they are not structured or easily machine readable; they just return text like "Transaction Created")
3. Capitalization is very inconsistent

It'd be nice if ShareASale integrated the APIs but I doubt they will.

**Comment by ooglek** [comment]
I posted the Merchant version of your code. Thanks!

https://github.com/ooglek/shareasale-merchant-api-sdk
https://packagist.org/packages/ooglek/shareasale-merchant-api-sdk

**Comment by orbex** [comment]
Awesome :) 
I'll update my readme to make it more clear that my code is Publisher-specific.
And add a link to your repo for people that are looking for Merchant code.
